# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upc', models.URLField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.URLField()),
                ('usage', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('amz', models.URLField()),
            ],
        ),
    ]
