# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amz',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(max_length=200),
        ),
    ]
